version: "3"

services:
  frontend:
    build: frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
  backend:
    build: backend
    container_name: backend
    secrets:
      - db-password
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/go/src
    depends_on:
      - frontend
  db:
    image: mysql:8.0.27
    container_name: db
    command: "--default-authentication-plugin=mysql_native_password"
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=traveling_alone
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 3306
    depends_on:
      - backend
  proxy:
    build: proxy
    container_name: proxy
    ports:
      - 80:80
    depends_on:
      - backend

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt
