services:
  frontend:
    build: frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app

  backend:
    build: backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/go/src
    depends_on:
      - frontend

  db:
    image: postgres:14.2-alpine
    container_name: db
    restart: always
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: pgsql
    expose:
      - 5432:5432
    depends_on:
      - backend

  proxy:
    build: proxy
    container_name: proxy
    ports:
      - 80:80
    depends_on:
      - backend
