version: "3"

services:
  frontend:
    build: frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
  backend:
    build: backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/go/src
    depends_on:
      - frontend
  db:
    build: db
    container_name: db
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    env_file:
      - ./db/.env
    expose:
      - 3306:3306
    depends_on:
      - backend
  proxy:
    build: proxy
    container_name: proxy
    ports:
      - 80:80
    depends_on:
      - backend
