// Code generated by ent, DO NOT EDIT.

package session

const (
	// Label holds the string label denoting the session type in the database.
	Label = "session"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldSession holds the string denoting the session field in the database.
	FieldSession = "session"
	// EdgeAccount holds the string denoting the account edge name in mutations.
	EdgeAccount = "account"
	// AccountFieldID holds the string denoting the ID field of the Account.
	AccountFieldID = "oid"
	// Table holds the table name of the session in the database.
	Table = "Sessions"
	// AccountTable is the table that holds the account relation/edge.
	AccountTable = "Sessions"
	// AccountInverseTable is the table name for the Account entity.
	// It exists in this package in order to avoid circular dependency with the "account" package.
	AccountInverseTable = "Accounts"
	// AccountColumn is the table column denoting the account relation/edge.
	AccountColumn = "account_id"
)

// Columns holds all SQL columns for session fields.
var Columns = []string{
	FieldID,
	FieldAccountID,
	FieldSession,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
